dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_lxml=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = pypy* ]]; then if_lxml=:; fi
install:
- $if_lxml pip install lxml
- pip install pydiatra pyflakes
script:
- ./inflacja 4237 PLZ --from=1984 --to=2012
- $if_lxml private/update-data
- git diff --exit-code
- python3 -m pydiatra .
- python3 -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
