dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
before_install:
- use_lxml=true
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]] || [[ $TRAVIS_PYTHON_VERSION = pypy* ]]; then use_lxml=false; fi
install:
- if $use_lxml; then pip install lxml; fi
- pip install pydiatra pyflakes
script:
- ./inflacja 4237 PLZ --from=1984 --to=2012
- if $use_lxml; then private/update-data; fi
- git diff --exit-code
- python3 -m pydiatra .
- python3 -m pyflakes .

# vim:ts=2 sts=2 sw=2 et
