#!/usr/bin/python3

# Copyright © 2016 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import os

import lxml.html

url = 'http://stat.gov.pl/obszary-tematyczne/ceny-handel/wskazniki-cen/wskazniki-cen-towarow-i-uslug-konsumpcyjnych-pot-inflacja-/roczne-wskazniki-cen-towarow-i-uslug-konsumpcyjnych-w-latach-1950-2014/'

here = os.path.dirname(__file__)
path = '{here}/../data'.format(here=here)

def main():
    doc = lxml.html.parse(url)
    [table] = doc.findall('//table[@class="tabelka-standard"]')
    data = {}
    for year_td in table.findall('.//td/strong'):
        year = int(year_td.text)
        [value_td] = year_td.xpath('./parent::td/following-sibling::td[1]')
        value = value_td.text
        if value == '\xA0':
            continue
        value = float(value.replace(',', '.')) / 100
        data[year] = value
    with open(path, 'wt', encoding='ASCII') as file:
        for year, value in sorted(data.items()):
            print('{y:4}\t{v:.3f}'.format(y=year, v=value), file=file)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
