#!/usr/bin/env python3

# Copyright © 2016 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import os

import lxml.html

url = 'http://stat.gov.pl/obszary-tematyczne/ceny-handel/wskazniki-cen/wskazniki-cen-towarow-i-uslug-konsumpcyjnych-pot-inflacja-/roczne-wskazniki-cen-towarow-i-uslug-konsumpcyjnych-w-latach-1950-2014/'

here = os.path.dirname(__file__)
path = '{here}/../data'.format(here=here)

def main():
    doc = lxml.html.parse(url)
    [table] = doc.findall('//table[@class="tabelka-standard"]')
    data = {}
    for year_td in table.findall('.//td/strong'):
        year = int(year_td.text)
        [value_td] = year_td.xpath('./parent::td/following-sibling::td[1]')
        value = value_td.text
        if value == '\xA0':
            continue
        value = float(value.replace(',', '.')) / 100
        data[year] = value
    with open(path, 'wt', encoding='ASCII') as file:
        for year, value in sorted(data.items()):
            print('{y:4}\t{v:.3f}'.format(y=year, v=value), file=file)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
