name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.11'
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: set up Python ${{matrix.python}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}
    - name: run tests
      run: |
        prove -v
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README
  data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: install lxml
      run: |
        sudo apt-get install -y python3-lxml
    - name: ensure data is up-to-date
      run: |
        private/update-data
        git diff --exit-code

# vim:ts=2 sts=2 sw=2 et
